// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Thoughts sidebar configuration
  thoughtsSidebar: [{type: 'autogenerated', dirName: 'thoughts'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  // Projects sidebar
  projectsSidebar: [{type: 'autogenerated', dirName: 'projects'}],
  
  // Workflow sidebar
  workflowSidebar: [{type: 'autogenerated', dirName: 'workflow'}],
  
  // Topics sidebar
  topicsSidebar: [
    'topics/welcome',
    {
      type: 'category',
      label: 'ML/AI',
      link: {
        type: 'doc',
        id: 'topics/ml-ai/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'topics/ml-ai',
        },
      ],
    },
    {
      type: 'category',
      label: 'Full Stack Development',
      link: {
        type: 'doc',
        id: 'topics/full-stack-development/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'topics/full-stack-development',
        },
      ],
    },
  ],
};

export default sidebars;
